### ISSUE TITLE
Make chchpd robust to addition of new columns in source spreadsheets

### ISSUE THREAD

**Issue by zenourn** [nzbri/chchpd#15] opened 2020-11-30 20:12 UTC
There are now several new columns that I need to add to the redcap exports. However, with the current design of `chchpd` requiring an exact number of columns in source files, this is extremely difficult to deploy as need to simultaneously:

 - Update source file to have additional columns
 - Update chchpd column specifications to use these new columns
 - Update every installed copy of chchpd (as existing installations will break with addition of new columns). 

I'm proposing that `chchpd` should ideally have an implementation such that it ignores any additional columns in source data files rather than this causing an error. This will make development much easier as can then update chchpd and deploy progressively and will also resolve issues that have occurred when users have inadvertently added new columns to spreadsheets. 

Is there any reason for not making this change? Is the current implementation for technical reasons only?

**Comment by m-macaskill** [comment] 2020-11-30 20:26
The current implementation is an intentional regression in functionality. Previously, it would read in a spreadsheet and then selectively alter the types of specified, named columns. This meant it should (generally) have been robust to both the number and ordering of columns (although we do make some assumptions about sequenced groups of columns with some imports). We had to re-write the importing code to work with an update to the `googlesheets` package to `googlesheets4`, which itself needed to be updated to deal with the new Google API. I've talked to the developer of those packages, such as here:
https://github.com/tidyverse/googlesheets4/issues/64#issuecomment-561864346

and this is what seems to be the latest status from Jenny in May:
https://github.com/tidyverse/googlesheets4/issues/156#issuecomment-632394202

So we might need to find our own workaround. I think @rezashr had some ideas on this?

**Comment by zenourn** [comment] 2020-11-30 20:54
Thanks. 

I think the strategy might be to read everything as characters and go for a custom parser. This should then also give the flexibility to handle the richness of the NAx codes which is needed for migration of several of the data sources and also more advanced imputation.

**Comment by m-macaskill** [comment] 2021-01-11 05:35
Fixed by https://github.com/nzbri/chchpd/pull/16

**Closed as completed by m-macaskill** 2021-01-11 05:35 UTC
Labels: enhancement
